# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  discord = {
    pname = "discord";
    version = "1vw602k7dzqm2zxic88jaw9pbg5w436x9h2y74f7jmn3wzdg5bm3";
    src = fetchTarball {
      url = "https://discord.com/api/download?platform=linux&format=tar.gz";
      sha256 = "12yrhlbigpy44rl3icir3jj2p5fqq2ywgbp5v3m1hxxmbawsm6wi";
    };
  };
  i3status-rust = {
    pname = "i3status-rust";
    version = "0ee6598173b242e4ee6f58817ef810497937fda9";
    src = fetchFromGitHub {
      owner = "greshake";
      repo = "i3status-rust";
      rev = "0ee6598173b242e4ee6f58817ef810497937fda9";
      fetchSubmodules = false;
      sha256 = "sha256-C+pqm5cIzUgc0oskmnjQqZ1t+Ty3MF/i5w/HuZFhRA8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./i3status-rust-0ee6598173b242e4ee6f58817ef810497937fda9/Cargo.lock;
      outputHashes = {
      };
    };
  };
}
