{...}: {
  pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
      MIIDDTCCAfWgAwIBAgIJAPj8SAqyDm3uMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
      BAMTCWxvY2FsaG9zdDAeFw0yNDA4MjcxNTAzNDBaFw0yNTA4MjcxNTAzNDBaMBQx
      EjAQBgNVBAMTCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
      ggEBAM2H2gFMDNXfESvNqbfMiU+E1AkH8Nl8zAKzkCFu2+bSCNib5hlCwxB2t/Ws
      /y+HhTh9YG7z7v+dzn0FnOP2ZKj5JhVPXt01V1G0kAaHUdfwEa/o9QbRykweTemu
      RyQ43K/RUdeZNISWXQ77jHgaOqytpTRFiSRePgbpwCMXQuvf6a/iBcqBMajEfqhF
      VfLs7Rtm8jFa6kE+aeDVFQuiz2a5/IcrFgrAuQXOab+yIqBYf0bvtrnTqlTUa6P2
      sfHIQ0fijv45I7ao78GgjNySDksEbf5mI6sRZQyvnlg6W+SkA/cPZTX9X0/9kfTS
      BVaJYPRIMNSPtlh0nxMbiAi8sa0CAwEAAaNiMGAwDAYDVR0TAQH/BAIwADAOBgNV
      HQ8BAf8EBAMCBaAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwEwFwYDVR0RAQH/BA0w
      C4IJbG9jYWxob3N0MA8GCisGAQQBgjdUAQEEAQIwDQYJKoZIhvcNAQELBQADggEB
      AL4GAelgu8kfT0gnjBJQxtS3vu+Ygubwz5iNvsYj2wUMNH3TSbIkhrD8CdwtrqcM
      YXdZ9N+7t343R5VGkKzOluBnxdwY8PxSsGcvtjopjKatiphPh4UPXtF2j8Bh7p2A
      7c2AAAV+HwKhO9FWYRThtvyYR0XJL5RX8k3A2yQvM6iaQLjC85m0hnsK+Fa/xBeQ
      hcsYcJFG/R2idFDuK2X28fhzv4jSSAZzjh2NDhh28AZNk+67J/WQxvYrO3nFhj7s
      WyHldW4I3GledFMhhVzFZt5BzAJA3qT+mXG7eDvUKic7K+zFDcDFv0qOZtX5EFUI
      8BKHh5JUIMP/gR2B+fx/ss8=
      -----END CERTIFICATE-----
    ''
  ];
}
